### PR TITLE
fix: increase recommended logo size, improve javascript, replace Twitter logo

### LINKED ISSUE #201: Increase size allocated for institutional logo
Currently supported logo size for webbook/network is 40 [height] x 265 [width]: https://github.com/pressbooks/pressbooks-aldine/blob/144da94e6fba9025ea82488afbe785a91132c416/inc/actions/namespace.php#L84-L91. Many institutions would like this to be larger (height wize) and less banner-like (ratio of less than 6.5:1, for example).

### LINKED ISSUE #235: Check if scrollTo target is a valid DOM element
### Description
We use a scrollTo function on Aldine which produces an error if the # target is not present (see below).  
https://github.com/pressbooks/pressbooks-aldine/blob/2b9ef72bc9717752f075fc6d70b93edd98fb98e2/assets/scripts/routes/common.js#L19-L25

Sentry Issue: [PRESSBOOKS-7D](https://sentry.io/organizations/pressbooks/issues/2147198507/?referrer=github_integration)

```
TypeError: t(...).scrollTo is not a function
  at None (/app/themes/pressbooks-aldine/dist/scripts/aldine.js:2:122430)
  at r (/app/plugins/pressbooks/assets/dist/scripts/sentry.js:2:80044)
```

### Steps to Reproduce

1. Visit the network home page for a Pressbooks network and append a `#string` to the URL which does not correspond to an existing id on the page.
2. Open the console to see the scrollTo JS error.

https://user-images.githubusercontent.com/13485451/113893845-40924a00-977c-11eb-9a4b-cfd0e2a231c8.mp4

**To fix:** could check if target exists before attempting to scrollTo or could replace with vanilla JS scrollTo behaviour (https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo).

### PR DESCRIPTION
**Pull request by SteelWagstaff**
This PR increases the recommended custom logo size (from 40x265 pixels to 140x560 pixels) in order to support the display of logos up to 70x280 pixels on Retina 2x monitors. Fixes https://github.com/pressbooks/pressbooks-aldine/issues/201. Note: will need to wait to be merged until new release of Aetna is updated in this repo. See https://github.com/pressbooks/aetna/pull/87

It addresses #198 by adding a new 'Header Background' option to the color customizer. Depends on https://github.com/pressbooks/pressbooks/pull/3867 and the open PR in Aetna.

It resolves https://github.com/pressbooks/pressbooks-aldine/issues/235 by making small improvements to the common.js javascript file.

It also replaces the Twitter logo (and label) with X's logo and label, replaces the link to the no longer maintained Pressbooks Twitter account in the footer with a link to our LinkedIn page, and adds three new social media options to the Customizer (for LinkedIn, YouTube, and Bluesky).

### CODE REVIEW

File: assets/scripts/routes/common.js [hunk 1]
```diff
@@ -14,38 +12,42 @@ export default {
...
+				// Scroll to anchor if there's a hash in the URL & anchor exists on the page
+				if (document.location.hash && document.location.hash !== '#') {
+					const anchorUponArrival = document.location.hash;
+					setTimeout(() => {
+						const $anchorElement = $(anchorUponArrival);
+						if ($anchorElement.length) {
+							$anchorElement.scrollTo({ duration: 1500 });
+							$anchorElement.trigger('focus');
+						} else {
+							console.warn(`Anchor element "${anchorUponArrival}" not found in the document.`);
```
Comment (richard015ar) [inline assets/scripts/routes/common.js:24]: I think we can delete this console.warn

File: assets/scripts/routes/common.js [hunk 2]
```diff
@@ -14,38 +12,42 @@ export default {
...
-			input.addEventListener(
-				'invalid',
-				event => {
-					input.classList.add( 'error' );
-				},
-				false
-			);
+			input.addEventListener('invalid', () => {
+					input.classList.add('error');
+				});
```
Comment (richard015ar) [inline assets/scripts/routes/common.js:40]: we have a linting issue here it seems

Comment (SteelWagstaff) [reply assets/scripts/routes/common.js:40]: I'm not seeing any locally. What's the issue? 
Screenshot 2024-12-16 155820

File: assets/scripts/routes/common.js (hunk 1 above)
Comment (SteelWagstaff) [reply assets/scripts/routes/common.js:24]: It could fail, silently, sure. I was adding it in case someone wanted to understand why the page didn't jump to the expected anchor point. Previously we were just throwing an error if the anchor wasn't present: https://github.com/pressbooks/pressbooks-aldine/issues/235. Happy to defer to your judgment about what's best

Comment (richard015ar) [reply assets/scripts/routes/common.js:24]: got it. I think it would be good to debug, maybe locally or on dev, but I am not sure if we want to print errors in the console in production for debugging purposes. In case we want to debug it in prod, maybe we could think of some strategy, such as sending it somewhere in the backend and putting it in the error logs?

Comment (SteelWagstaff) [reply assets/scripts/routes/common.js:24]: I wasn't intending it to be used for debugging by a developer, but to inform the browser user. If, for example, as a reader I pasted a link that looks like this: `https://pressbooks.pub/mybook/#fake` but the fake anchor doesn't exist in the page, I might be surprised that the page doesn't load at the expected anchor. Opening the browser console would display a warning message telling me that the anchor `fake` doesn't exist on the page so I could correct or update the URL path. It was purely intended for informational purposes. If you don't think it's helpful, let me know, and I can remove it -- it would be a simple commit to take it out.

**Comment by SteelWagstaff** [comment]
FYI: new Aetna release has been made and bump was added to this PR.

**Review by arzola — APPROVED** [review]
LGTM I tested all of this changes and works as expected
