### PR TITLE
Fixes for #71

### LINKED ISSUE #71: Catalog visibility fix
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Aldine](http://github.com/pressbooks/pressbooks-aldine/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing the issue while using Aldine as your network's root theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-aldine) to see if your bug or enhancement is already listed?

### Description

Catalog should be hidden automatically if no public books; Catalog page should not be editable.

See:

+ https://github.com/WordPress/WordPress/blob/master/wp-admin/edit-form-advanced.php#L73

### Steps to Reproduce

Not applicable.

### System Information

Aldine: 1.0-beta.1

### PR DESCRIPTION
**Pull request by greatislander**
Fix #71:

- Redirect empty catalog to 404
- Hide empty landing page catalog
- Hide content editor for catalog page

### CODE REVIEW

File: inc/actions/namespace.php [hunk 1]
```diff
@@ -202,3 +202,21 @@ function output_custom_colors() {
 function remove_admin_bar_callback() {
 	remove_action( 'wp_head', '_admin_bar_bump_cb' );
 }
+
+/**
+ * Hide content editor for Catalog page.
+ */
+function hide_catalog_content_editor() {
+	$post_id = isset( $_GET['post'] ) ? $_GET['post'] : null ;
```
Comment (connerbw) [inline inc/actions/namespace.php]: PHP7 supports this syntax:

`$post_id =  $_GET['post'] ?? null`

No need to change it, but in case you want a shorter version for the future.
